keys:
  evmPrivateEncrypted: wVGm8062MsfXY9rWY4zRAxDSXaVtSXGwMyf0e5--MGEiyo09NqHw_pl5FdsOJt7c1906uMO7kGxdiAoG7e_kEwqnCpRqvdjLkNNap9qcYM0Xy722ESlrepLIn-TgIpP-dTLWhAm7erYsk7t-bTDmYQ

features:
  assistivePricing: true
  newContributorGreeting:
    enabled: true
  publicAccessControl:
    setLabel: true
    fundExternalClosedIssue: true

payments:
  evmNetworkId: 100
  basePriceMultiplier: 2
  issueCreatorMultiplier: 3
  maxPermitPrice: 1000

timers:
  reviewDelayTolerance: 30 days
  taskStaleTimeoutDuration: 30 days
  taskFollowUpDuration: 3.5 days
  taskDisqualifyDuration: 7 days

miscellaneous:
  promotionComment: "<h6>If you've enjoyed your experience in the DevPool, we'd appreciate your support. Follow <a href='https://github.com/ubiquity'>Ubiquity on GitHub</a> and star <a href='https://github.com/ubiquity/devpool-directory'>this repo</a>. Your endorsement means the world to us and helps us grow!</h6><h6>We are excited to announce that the DevPool and UbiquiBot are now available to partners! Our ideal collaborators are globally distributed crypto-native organizations, who actively work on open source on GitHub, and excel in research & development. If you can introduce us to the repository maintainers in these types of companies, we have a special bonus in store for you!</h6>"
  maxConcurrentTasks: 2
  registerWalletWithVerification: false

disabledCommands: []

incentives:
  comment:
    elements:
      code: 1
      img: 0
      h1: 1
      h2: 1
      h3: 1
      h4: 1
      h5: 1
      h6: 1
      li: 0.5
      a: 1
      blockquote: 0
      i: 0
    totals:
      word: 0.1

labels:
  time:
    - "Time: <1 Hour"
    - "Time: <2 Hours"
    - "Time: <4 Hours"
    - "Time: <1 Day"
    - "Time: <1 Week"
  priority:
    - "Priority: 1 (Normal)"
    - "Priority: 2 (Medium)"
    - "Priority: 3 (High)"
    - "Priority: 4 (Urgent)"
    - "Priority: 5 (Emergency)"
